// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CPUUsage():Promise<number>;

export function DiskUsage():Promise<number>;
